In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(filepath_or_buffer="./ifood_df.csv",sep=",",header=0).rename(columns=str.lower)
df.head(10)

income  kidhome  teenhome  recency  mntwines  mntfruits  mntmeatproducts  \
0  58138.0        0         0       58       635         88              546   
1  46344.0        1         1       38        11          1                6   
2  71613.0        0         0       26       426         49              127   
3  26646.0        1         0       26        11          4               20   
4  58293.0        1         0       94       173         43              118   
5  62513.0        0         1       16       520         42               98   
6  55635.0        0         1       34       235         65              164   
7  33454.0        1         0       32        76         10               56   
8  30351.0        1         0       19        14          0               24   
9   5648.0        1         1       68        28          0                6   

   mntfishproducts  mntsweetproducts  mntgoldprods  ...  marital_together  \
0              172                88            88  ...                 0   
1                2                 1             6  ...                 0   
2              111                21            42  ...                 1   
3               10                 3             5  ...                 1   
4               46                27            15  ...                 0   
5                0                42            14  ...                 1   
6               50                49            27  ...                 0   
7                3                 1            23  ...                 0   
8                3                 3             2  ...                 1   
9                1                 1            13  ...                 1   

   marital_widow  education_2n cycle  education_basic  education_graduation  \
0              0                   0                0                     1   
1              0                   0                0                     1   
2              0                   0                0                     1   
3              0                   0                0                     1   
4              0                   0                0                     0   
5              0                   0                0                     0   
6              0                   0                0                     1   
7              0                   0                0                     0   
8              0                   0                0                     0   
9              0                   0                0                     0   

   education_master  education_phd  mnttotal  mntregularprods  \
0                 0              0      1529             1441   
1                 0              0        21               15   
2                 0              0       734              692   
3                 0              0        48               43   
4                 0              1       407              392   
5                 1              0       702              688   
6                 0              0       563              536   
7                 0              1       146              123   
8                 0              1        44               42   
9                 0              1        36               23   

   acceptedcmpoverall  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0  
5                   0  
6                   0  
7                   0  
8                   0  
9                   1  

[10 rows x 39 columns]

In [6]:
df.shape

(2205, 39)

In [7]:
df.columns

Index(['income', 'kidhome', 'teenhome', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response',
       'age', 'customer_days', 'marital_divorced', 'marital_married',
       'marital_single', 'marital_together', 'marital_widow',
       'education_2n cycle', 'education_basic', 'education_graduation',
       'education_master', 'education_phd', 'mnttotal', 'mntregularprods',
       'acceptedcmpoverall'],
      dtype='object')

In [8]:
df[["education_basic","income","response","recency"]].head()

education_basic   income  response  recency
0                0  58138.0         1       58
1                0  46344.0         0       38
2                0  71613.0         0       26
3                0  26646.0         0       26
4                0  58293.0         0       94

In [9]:
df.response.head()

0    1
1    0
2    0
3    0
4    0
Name: response, dtype: int64

In [10]:
df["response"].head()

0    1
1    0
2    0
3    0
4    0
Name: response, dtype: int64

In [13]:
#Con filter(regex="nombre_columna") se muestran las columnas que tienen ese mismo nombre.
df.filter(regex="accepted").head()

acceptedcmp3  acceptedcmp4  acceptedcmp5  acceptedcmp1  acceptedcmp2  \
0             0             0             0             0             0   
1             0             0             0             0             0   
2             0             0             0             0             0   
3             0             0             0             0             0   
4             0             0             0             0             0   

   acceptedcmpoverall  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0

In [12]:
df.filter(regex="education").head()

education_2n cycle  education_basic  education_graduation  \
0                   0                0                     1   
1                   0                0                     1   
2                   0                0                     1   
3                   0                0                     1   
4                   0                0                     0   

   education_master  education_phd  
0                 0              0  
1                 0              0  
2                 0              0  
3                 0              0  
4                 0              1

In [14]:
df.filter(regex="home").head()

kidhome  teenhome
0        0         0
1        1         1
2        0         0
3        1         0
4        1         0

In [19]:
#Con loc no se usa doble corchetes para seleccionar varias columnas.
#Simplemente en cuál empieza, y en cuál termina.
df.loc[:,"kidhome":"numwebpurchases"].head()

kidhome  teenhome  recency  mntwines  mntfruits  mntmeatproducts  \
0        0         0       58       635         88              546   
1        1         1       38        11          1                6   
2        0         0       26       426         49              127   
3        1         0       26        11          4               20   
4        1         0       94       173         43              118   

   mntfishproducts  mntsweetproducts  mntgoldprods  numdealspurchases  \
0              172                88            88                  3   
1                2                 1             6                  2   
2              111                21            42                  1   
3               10                 3             5                  2   
4               46                27            15                  5   

   numwebpurchases  
0                8  
1                1  
2                8  
3                2  
4                5

In [31]:
#Con iloc si se usa doble corchetes, por que se forma una lista.
#Se seleccionan las comunas con sus indices, una por una.
df.iloc[:,[1,2,5]].head()

kidhome  teenhome  mntfruits
0        0         0         88
1        1         1          1
2        0         0         49
3        1         0          4
4        1         0         43

In [30]:
df

income  kidhome  teenhome  recency  mntwines  mntfruits  \
0     58138.0        0         0       58       635         88   
1     46344.0        1         1       38        11          1   
2     71613.0        0         0       26       426         49   
3     26646.0        1         0       26        11          4   
4     58293.0        1         0       94       173         43   
...       ...      ...       ...      ...       ...        ...   
2200  61223.0        0         1       46       709         43   
2201  64014.0        2         1       56       406          0   
2202  56981.0        0         0       91       908         48   
2203  69245.0        0         1        8       428         30   
2204  52869.0        1         1       40        84          3   

      mntmeatproducts  mntfishproducts  mntsweetproducts  mntgoldprods  ...  \
0                 546              172                88            88  ...   
1                   6                2                 1             6  ...   
2                 127              111                21            42  ...   
3                  20               10                 3             5  ...   
4                 118               46                27            15  ...   
...               ...              ...               ...           ...  ...   
2200              182               42               118           247  ...   
2201               30                0                 0             8  ...   
2202              217               32                12            24  ...   
2203              214               80                30            61  ...   
2204               61                2                 1            21  ...   

      marital_together  marital_widow  education_2n cycle  education_basic  \
0                    0              0                   0                0   
1                    0              0                   0                0   
2                    1              0                   0                0   
3                    1              0                   0                0   
4                    0              0                   0                0   
...                ...            ...                 ...              ...   
2200                 0              0                   0                0   
2201                 1              0                   0                0   
2202                 0              0                   0                0   
2203                 1              0                   0                0   
2204                 0              0                   0                0   

      education_graduation  education_master  education_phd  mnttotal  \
0                        1                 0              0      1529   
1                        1                 0              0        21   
2                        1                 0              0       734   
3                        1                 0              0        48   
4                        0                 0              1       407   
...                    ...               ...            ...       ...   
2200                     1                 0              0      1094   
2201                     0                 0              1       436   
2202                     1                 0              0      1217   
2203                     0                 1              0       782   
2204                     0                 0              1       151   

      mntregularprods  acceptedcmpoverall  
0                1441                   0  
1                  15                   0  
2                 692                   0  
3                  43                   0  
4                 392                   0  
...               ...                 ...  
2200              847                   0  
2201              428                   1  
2202             1193                   1  
2203       

In [5]:
#Aquí
list=[1,2,3,4,5,6,7,8,9]
list=np.array(list)

In [6]:
list

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#indice negativo indica que desde atrás.
list[-3]

7

In [8]:
#Con los 2 puntos después del indice negativo indica que hasta el final.
list[-3:]

array([7, 8, 9])

In [9]:
neo=[[1,2,3],[4,5,6],[7,8,9]]
neo=np.array(neo)

In [10]:
neo

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#En las matrices también se manejan indices desde 0, y cada línea es uno de ellos.
neo[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [18]:
#Selección de filas, y columnas en una matriz
neo[0,0:2]

array([1, 2])

In [20]:
neo[0,1:3]

array([2, 3])

In [23]:
neo[0,2]

3

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#Convertir un arreglo númerico en alfanúmerico. 
list=list.astype(np.string_)

In [26]:
list

array([b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9'], dtype='|S11')

In [30]:
list.dtype

dtype('S11')

In [31]:
list=list.astype(np.bool_)

In [32]:
list

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [33]:
list

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])