In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
trozo=arr[0:6]
trozo

array([0, 0, 0, 0, 0, 0])

In [8]:
trozo[:]=0
trozo

array([0, 0, 0, 0, 0, 0])

In [9]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [10]:
copia=arr.copy()

In [11]:
copia

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [12]:
copia[:]=100

In [13]:
copia

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])