In [2]:
import pandas as pd
import numpy as np

In [4]:
scalar=np.array(42)
scalar

array(42)

In [5]:
scalar.ndim

0

In [9]:
vector=np.array([1,2,3,])
vector

array([1, 2, 3])

In [11]:
vector.ndim

1

In [22]:
matriz=np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz.ndim

2

In [95]:
tensor=np.array([[[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]]]])

In [96]:
tensor.ndim

4

In [97]:
tensor0=np.squeeze(tensor)
tensor0.ndim

3

In [34]:
tensor

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [58]:
#Agregar o eliminar dimensiones
vector=np.array([1,2,3],ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [55]:
#np.expand_dims() expande el número de dimensiones
expand=np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [61]:
print(vector,vector.ndim)
vector2=np.squeeze(vector)
print(vector2,vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


In [84]:
tensor2=np.array([[[[[1,2,3],[4,5,6],[7,8,9],[1,2,3],[4,5,6],[7,8,9]]]]])
tensor2.ndim

5

In [86]:
tensor3=np.expand_dims(np.array(tensor2),axis=0)
tensor3.ndim

6

In [88]:
tensor4=np.squeeze(tensor3)
tensor4.ndim

2

In [89]:
print(tensor.ndim,tensor2.ndim,tensor3.ndim,tensor4.ndim)

3 5 6 2
