In [1]:
import numpy as np

In [4]:
arr=np.random.randint(1,20,10)
arr

array([ 5, 12,  3,  9,  6,  3, 15, 19, 16, 18])

In [5]:
arr.shape

(10,)

In [7]:
matriz=arr.reshape(2,5)
matriz

array([[ 5, 12,  3,  9,  6],
       [ 3, 15, 19, 16, 18]])

In [8]:
arr.max()

19

In [9]:
matriz.max()

19

In [10]:
#En las matrices el eje 1 es para filas
matriz.max(1)

array([12, 19])

In [11]:
#Y el eje 0 es para columnas
matriz.max(0)

array([ 5, 15, 19, 16, 18])

In [12]:
#argmax() muestra el indice del valor máximo
matriz.argmax()

7

In [16]:
print(matriz)

[[ 5 12  3  9  6]
 [ 3 15 19 16 18]]


In [15]:
matriz.argmax(0)

array([0, 1, 1, 1, 1], dtype=int64)

In [17]:
matriz.argmax(1)

array([1, 2], dtype=int64)

In [18]:
arr.min()

3

In [19]:
arr

array([ 5, 12,  3,  9,  6,  3, 15, 19, 16, 18])

In [26]:
arr.argmin()

2

In [27]:
#Muestra la cantidad del número menor al mayor
arr.ptp()

16

In [28]:
matriz.ptp()

16

In [29]:
#Muestra el valor que está en la mitad. (El 50%)
np.percentile(arr,50)

10.5

In [30]:
np.percentile(arr,100)

19.0

In [31]:
#Organiza de menor a mayor los valores en el arreglo.
arr.sort()
arr

array([ 3,  3,  5,  6,  9, 12, 15, 16, 18, 19])

In [32]:
np.median(arr)

10.5

In [34]:
matriz

array([[ 3,  3,  5,  6,  9],
       [12, 15, 16, 18, 19]])

In [33]:
np.median(matriz,0)

array([ 7.5,  9. , 10.5, 12. , 14. ])

In [36]:
np.median(matriz,1)

array([ 5., 16.])

In [38]:
np.std(arr)

5.885575587824865

In [39]:
np.std(matriz,0)

array([4.5, 6. , 5.5, 6. , 5. ])

In [40]:
np.std(matriz,1)

array([2.22710575, 2.44948974])

In [41]:
np.std(matriz)

5.885575587824865

In [42]:
#La desviación estandar al cuadrado es igual a la variación
np.std(arr)**2

34.64

In [43]:
np.var(arr)

34.64

In [44]:
np.mean(arr)

10.6

In [102]:
a=np.array([[1,2],[3,4]])
b=np.array([5,6])

In [103]:
np.concatenate((a,b),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [93]:
b=np.squeeze(b)
b

array([7, 8, 9])

In [105]:
b=np.expand_dims(b,axis=0)
b

array([[5, 6]])

In [109]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
a

array([[1, 2],
       [3, 4]])

In [106]:
b

array([[5, 6]])

In [108]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])