In [1]:
import numpy as np

In [2]:
lista=[1,2]
lista

[1, 2]

In [4]:
arr=np.arange(0,10)
arr2=arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [8]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [9]:
arr*arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
matriz=arr.reshape(2,5)
matriz2=matriz.copy()

In [30]:
matriz.reshape(5,2)
matriz2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
#Producto punto
np.matmul(matriz,matriz2)

array([[ 60,  70],
       [160, 195]])

In [35]:
matriz.shape

(2, 5)

In [36]:
matriz2.shape

(5, 2)

In [40]:
#Producto punto (forma corta)
matriz@matriz2

array([[ 60,  70],
       [160, 195]])